version: 2.1

jobs:
  build-and-test:
    macos:
      xcode: 11.5.0
    shell: zsh

    steps:
      - checkout
      - run:
          name: Install dependencies
          command: brew install swiftlint && brew install wget && cd src/xcode && bundle install
      - run:
          name: Build
          command: cd src/xcode && bundle exec fastlane build
      - run:
          name: Tests
          command: cd src/xcode && bundle exec fastlane test
      - sonarcloud/scan:
          os: macosx
          cache_version:
      - store_test_results:
          path: src/xcode/fastlane/test_output
      - store_artifacts:
          path: src/xcode/fastlane/test_output

  grab-screenshots:
    macos:
      xcode: 11.5.0
    steps:
      - checkout
      - run: cd src/xcode && bundle install
      - run:
          name: Snapshots
          command: cd src/xcode && bundle exec fastlane snapshot
      - store_artifacts:
          path: src/xcode/screenshots

orbs:
  sonarcloud: tkowark/sonarcloud2@0.1.0
workflows:
    default:
      jobs:
        - build-and-test
